### ISSUE TITLE
Mod request (Ad Astra!)

### ISSUE THREAD

**Issue by chamychu** [Coney-Poney/workingtitle-modpack#2]
it would be nice seeing this mod in the pack :) 
https://modrinth.com/mod/ad-astra

**Comment by celestecaprine** [comment]
As fun as it would be to send ponies off to the moon, It seems to be a little self-contained for my liking? It appears to have it's own means of generating energy, collecting fuel, etc.

This will be something I consider down the line once the mod list is more matured, but I don't know how well I can cram space travel into this pack.

**Comment by chamychu** [comment]
fair tbh 
i just thought since it wasn't as big as galactic craft it would be fine to have :>
but im glad you are considering adding this in the future tho :D
