### ISSUE TITLE
Chamy's requests

### ISSUE THREAD

**Issue by chamychu** [Coney-Poney/workingtitle-modpack#3]
Ok so there are a lot of mods that i want to request so i just thought i would make a list and you can pick the ones you think should be added to the pack :) [Chamy's mod requests.txt](https://github.com/Coney-Poney/workingtitle-modpack/files/10493766/Chamy.s.mod.requests.txt)

(i made sure they are all 1.19.3 compatible)

**Comment by celestecaprine** [comment]
So I can reference this later, I'ma just...

- [Dimensional Doors](https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors)
- [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
- [No Chat Reports](https://modrinth.com/mod/no-chat-reports)
- [Creeper Overhaul](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
- [Croptopia](https://www.curseforge.com/minecraft/mc-mods/croptopia)
- [Ferrite Core](https://modrinth.com/mod/ferrite-core)
- [Sound Physics Remastered](https://modrinth.com/mod/sound-physics-remastered)
- [LambDynamicLights](https://modrinth.com/mod/lambdynamiclights)
- [Farmer's Delight](https://modrinth.com/mod/farmers-delight-fabric)
- [Anti-Ghost](https://modrinth.com/mod/antighost)
- [Adorn](https://modrinth.com/mod/adorn)
- [Dimthread](https://modrinth.com/mod/dimthread)
- [Better Ping Display](https://modrinth.com/mod/better-ping-display-fabric)
- [Bits and Chisels](https://modrinth.com/mod/bits-and-chisels)
- [CraftPresence](https://modrinth.com/mod/craftpresence)
- [Extra Alchemy](https://modrinth.com/mod/extraalchemy)
- [Grappling Hook](https://modrinth.com/mod/grappling-hook-mod)
- [Pet Owner](https://modrinth.com/mod/petowner)
- [Universal Graves](https://modrinth.com/mod/universal-graves)
- [Purpeille](https://modrinth.com/mod/purpeille)
- [Things](https://modrinth.com/mod/things)
- [Campanion](https://modrinth.com/mod/campanion)
- [Right-Click Harvest](https://modrinth.com/mod/rightclickharvest)
- [Infusion Table](https://github.com/jptrzy/infusion-table-mod)
- [Harvest Scythes](https://modrinth.com/mod/harvest-scythes)
- [LambdaBetterGrass](https://modrinth.com/mod/lambdabettergrass)

I'll look over these as I get started with adding the proper content mods!

**Comment by chamychu** [comment]
okay sounds good!

**Comment by celestecaprine** [comment]
Added some of the mods from this list, if there's any that remain that you think I should add, lemme know and I can provide some feedback on why or why not I'd include it in the pack. Thank you!
