### ISSUE TITLE
Limit mod request

### ISSUE THREAD

**Issue by Lim-it** [Coney-Poney/workingtitle-modpack#4]
So this list is basically some mods that i think would be cool to see in the modpack hehe  
+ [Survivality](https://modrinth.com/mod/survivality)
+ [Things](https://modrinth.com/mod/things)
> Need [Patchouli](https://modrinth.com/mod/patchouli), [Trinkets](https://modrinth.com/mod/trinkets), [owo](https://modrinth.com/mod/owo-lib),,,,,, 
+ [Automobility](https://modrinth.com/mod/automobility)
+ [Particle Moths](https://modrinth.com/mod/particle-moths)
+ Create addons (yay):
    + [Create: Crystal Clear Refabricated](https://modrinth.com/mod/create-crystal-clear-fabric)
	+ [Create Addition](https://www.curseforge.com/minecraft/mc-mods/createaddition)
	+ [Create Extended Flywheels](https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels-fabric/files)
	+ [Create Extended Cogwheels](https://www.curseforge.com/minecraft/mc-mods/create-extended-cogwheels-fabric)
	+ [Create Deco](https://www.curseforge.com/minecraft/mc-mods/create-deco)  
  
EDIT: I FORGOT THE FUNNY [DOOR MOD](https://modrinth.com/mod/half-doors)

**Comment by celestecaprine** [comment]
Added some of the mods from this list, if there's any that remain that you think I should add, lemme know and I can provide some feedback on why or why not I'd include it in the pack. Thank you!
