### ISSUE TITLE
Don and Rose's Mod Requests

### ISSUE THREAD

**Issue by Rose-French** [Coney-Poney/workingtitle-modpack#5]
[REI](https://modrinth.com/mod/roughly-enough-items) 
[Farmer's Delight](https://modrinth.com/mod/farmers-delight-fabric) 
[Artifacts](https://modrinth.com/mod/artifacts) 
[Stack Refill](https://modrinth.com/mod/stack-refill) 
[Inspecio](https://modrinth.com/mod/inspecio)
[Spellbound Enchantments](https://modrinth.com/mod/spellbound-enchantments) (May need to disable one or two) 
[Oxidized](https://modrinth.com/mod/oxidized)
[Additional Additions](https://modrinth.com/mod/addadd)
[Bundle Jumble](https://modrinth.com/mod/bundle-jumble) (please 😳)
[Another Emerald Addon](https://modrinth.com/mod/another-emerald-mod) 
[Spelunkery](https://modrinth.com/mod/spelunkery) 
[Towns and Towers](https://modrinth.com/mod/towns-and-towers) 
[LambDynamicLights](https://modrinth.com/mod/lambdynamiclights) 
[Wanderer's Catalogue](https://modrinth.com/mod/wanderers-catalogue) 
[Nyfs Quivers](https://modrinth.com/mod/nyfs-quivers) 
[Keep Some Inventory](https://modrinth.com/datapack/keep-some-inventory) 
[Pluckable Arrows](https://modrinth.com/mod/pluckablearrows) 
[Immersive Armors](https://modrinth.com/mod/immersive-armors) 
[Creeper Spores](https://modrinth.com/mod/creeper-spores) 
[Microdurability](https://modrinth.com/mod/microdurability) 
[Enhanced Gear](https://modrinth.com/mod/enhanced-gear) 

[Currently unable to use but looks really cool]
[Scriptor Magicae](https://modrinth.com/mod/scriptor-magicae)

**Comment by celestecaprine** [comment]
Added some of the mods from this list, if there's any that remain that you think I should add, lemme know and I can provide some feedback on why or why not I'd include it in the pack. Thank you!
